import { MigrationInterface, QueryRunner } from "typeorm";

export class AddedAwardMovieActor1721646198033 implements MigrationInterface {
    name = 'AddedAwardMovieActor1721646198033'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "award" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(300) NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "UQ_4ba41d909c8b2592f9516435524" UNIQUE ("id", "uuid"), CONSTRAINT "PK_e887e4e69663925ebb60d3a7775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "award_movie_actor" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" character varying(300) NOT NULL, "description" character varying(300) NOT NULL, "movieId" integer, "actorId" integer, "awardId" integer, CONSTRAINT "PK_4ee44bbf1b528633888b38fc908" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "award_movie_actor" ADD CONSTRAINT "FK_d7b319ca54587443a6e21d07a9f" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "award_movie_actor" ADD CONSTRAINT "FK_b212ce71a586e58466d24aac018" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "award_movie_actor" ADD CONSTRAINT "FK_cb98c188aa5ed27024f37755008" FOREIGN KEY ("awardId") REFERENCES "award"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "award_movie_actor" DROP CONSTRAINT "FK_cb98c188aa5ed27024f37755008"`);
        await queryRunner.query(`ALTER TABLE "award_movie_actor" DROP CONSTRAINT "FK_b212ce71a586e58466d24aac018"`);
        await queryRunner.query(`ALTER TABLE "award_movie_actor" DROP CONSTRAINT "FK_d7b319ca54587443a6e21d07a9f"`);
        await queryRunner.query(`DROP TABLE "award_movie_actor"`);
        await queryRunner.query(`DROP TABLE "award"`);
    }

}
