import { MigrationInterface, QueryRunner } from "typeorm";

export class NewEntityMovieActor1721557597812 implements MigrationInterface {
    name = 'NewEntityMovieActor1721557597812'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "movie_actor" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "character" character varying(300) NOT NULL, "movieId" integer, "actorId" integer, CONSTRAINT "PK_c578a5152d4c32b9ad0bfa7c867" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "movie_actor" ADD CONSTRAINT "FK_df7c2fa133a021b2ce7c1785b05" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movie_actor" ADD CONSTRAINT "FK_528cb7d2a0c17e05421ab148816" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "movie_actor" DROP CONSTRAINT "FK_528cb7d2a0c17e05421ab148816"`);
        await queryRunner.query(`ALTER TABLE "movie_actor" DROP CONSTRAINT "FK_df7c2fa133a021b2ce7c1785b05"`);
        await queryRunner.query(`DROP TABLE "movie_actor"`);
    }

}
