// import { MigrationInterface, QueryRunner } from "typeorm";

// export class UpdateMovieEntity1722162068011 implements MigrationInterface {
//     name = 'UpdateMovieEntity1722162068011'

//     public async up(queryRunner: QueryRunner): Promise<void> {
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "createdAt"`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "updatedAt"`);
//         await queryRunner.query(`ALTER TABLE "award" ADD "uuid" character varying default NULL`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD "id" SERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP CONSTRAINT "PK_e592fd44ed9b5cfd791a9d5d8eb"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD CONSTRAINT "PK_d37431a574500c808f3a800cac4" PRIMARY KEY ("year", "id")`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP CONSTRAINT "FK_a32a80a88aff67851cf5b75d1cb"`);
//         await queryRunner.query(`ALTER TABLE "director" DROP CONSTRAINT "PK_b85b179882f31c43324ef124fea"`);
//         await queryRunner.query(`ALTER TABLE "director" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "director" ADD "id" SERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "director" ADD CONSTRAINT "PK_b85b179882f31c43324ef124fea" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "FK_48fa78b2634b01bf58ad1686ef5"`);
//         // await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "PK_05b325494fcc996a44ae6928e5e"`);
//         await queryRunner.query(`ALTER TABLE "actor" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "actor" ADD "id" SERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "PK_05b325494fcc996a44ae6928e5e" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP CONSTRAINT "FK_3cd871b4c3635fb5e6cbcb3b668"`);
//         await queryRunner.query(`ALTER TABLE "award" DROP CONSTRAINT "PK_e887e4e69663925ebb60d3a7775"`);
//         await queryRunner.query(`ALTER TABLE "award" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "award" ADD "id" SERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "award" ADD CONSTRAINT "PK_e887e4e69663925ebb60d3a7775" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP COLUMN "awardId"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD "awardId" integer`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "FK_45708bd514560bac8a3a54470d5"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP CONSTRAINT "FK_eb945538031ede2cc23d3ddaa2b"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_48fa78b2634b01bf58ad1686ef5" PRIMARY KEY ("actorId")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP COLUMN "movieId"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD "movieId" integer NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_48fa78b2634b01bf58ad1686ef5"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a" PRIMARY KEY ("actorId", "movieId")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_45708bd514560bac8a3a54470d5" PRIMARY KEY ("movieId")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP COLUMN "actorId"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD "actorId" integer NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_45708bd514560bac8a3a54470d5"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a" PRIMARY KEY ("movieId", "actorId")`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP CONSTRAINT "FK_87faa2eaa3fdf780320e643c9c0"`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP CONSTRAINT "PK_cb3bb4d61cf764dc035cbedd422"`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "id" SERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD CONSTRAINT "PK_cb3bb4d61cf764dc035cbedd422" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "directorId"`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "directorId" integer`);
//         await queryRunner.query(`ALTER TABLE "writer" DROP CONSTRAINT "PK_e43f7a41e79384a71f5e201c323"`);
//         await queryRunner.query(`ALTER TABLE "writer" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "writer" ADD "id" SERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "writer" ADD CONSTRAINT "PK_e43f7a41e79384a71f5e201c323" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP CONSTRAINT "PK_fc5daf3b5918b511f3f674afb52"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD CONSTRAINT "PK_9093f672399cb51b4164926a08f" PRIMARY KEY ("festivalId")`);
//         await queryRunner.query(`DROP INDEX "public"."IDX_87faa2eaa3fdf780320e643c9c"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP COLUMN "movieId"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD "movieId" integer NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP CONSTRAINT "PK_9093f672399cb51b4164926a08f"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD CONSTRAINT "PK_fc5daf3b5918b511f3f674afb52" PRIMARY KEY ("festivalId", "movieId")`);
//         await queryRunner.query(`CREATE INDEX "IDX_87faa2eaa3fdf780320e643c9c" ON "festival_movies_movie" ("movieId") `);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD CONSTRAINT "FK_eb945538031ede2cc23d3ddaa2b" FOREIGN KEY ("actorMoviesMovieMovieId", "actorMoviesMovieActorId") REFERENCES "actor_movies_movie"("movieId","actorId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD CONSTRAINT "FK_3cd871b4c3635fb5e6cbcb3b668" FOREIGN KEY ("awardId") REFERENCES "award"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "FK_45708bd514560bac8a3a54470d5" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "FK_48fa78b2634b01bf58ad1686ef5" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD CONSTRAINT "FK_a32a80a88aff67851cf5b75d1cb" FOREIGN KEY ("directorId") REFERENCES "director"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD CONSTRAINT "FK_87faa2eaa3fdf780320e643c9c0" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//     }

//     public async down(queryRunner: QueryRunner): Promise<void> {
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP CONSTRAINT "FK_87faa2eaa3fdf780320e643c9c0"`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP CONSTRAINT "FK_a32a80a88aff67851cf5b75d1cb"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "FK_48fa78b2634b01bf58ad1686ef5"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "FK_45708bd514560bac8a3a54470d5"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP CONSTRAINT "FK_3cd871b4c3635fb5e6cbcb3b668"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP CONSTRAINT "FK_eb945538031ede2cc23d3ddaa2b"`);
//         await queryRunner.query(`DROP INDEX "public"."IDX_87faa2eaa3fdf780320e643c9c"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP CONSTRAINT "PK_fc5daf3b5918b511f3f674afb52"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD CONSTRAINT "PK_9093f672399cb51b4164926a08f" PRIMARY KEY ("festivalId")`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP COLUMN "movieId"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD "movieId" bigint NOT NULL`);
//         await queryRunner.query(`CREATE INDEX "IDX_87faa2eaa3fdf780320e643c9c" ON "festival_movies_movie" ("movieId") `);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" DROP CONSTRAINT "PK_9093f672399cb51b4164926a08f"`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD CONSTRAINT "PK_fc5daf3b5918b511f3f674afb52" PRIMARY KEY ("festivalId", "movieId")`);
//         await queryRunner.query(`ALTER TABLE "writer" DROP CONSTRAINT "PK_e43f7a41e79384a71f5e201c323"`);
//         await queryRunner.query(`ALTER TABLE "writer" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "writer" ADD "id" BIGSERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "writer" ADD CONSTRAINT "PK_e43f7a41e79384a71f5e201c323" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "directorId"`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "directorId" bigint`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP CONSTRAINT "PK_cb3bb4d61cf764dc035cbedd422"`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "id" BIGSERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD CONSTRAINT "PK_cb3bb4d61cf764dc035cbedd422" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "festival_movies_movie" ADD CONSTRAINT "FK_87faa2eaa3fdf780320e643c9c0" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_45708bd514560bac8a3a54470d5" PRIMARY KEY ("movieId")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP COLUMN "actorId"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD "actorId" bigint NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_45708bd514560bac8a3a54470d5"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a" PRIMARY KEY ("actorId", "movieId")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_48fa78b2634b01bf58ad1686ef5" PRIMARY KEY ("actorId")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP COLUMN "movieId"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD "movieId" bigint NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" DROP CONSTRAINT "PK_48fa78b2634b01bf58ad1686ef5"`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "PK_bb8e9dcbccde7d3edd9383fb25a" PRIMARY KEY ("actorId", "movieId")`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD CONSTRAINT "FK_eb945538031ede2cc23d3ddaa2b" FOREIGN KEY ("actorMoviesMovieMovieId", "actorMoviesMovieActorId") REFERENCES "actor_movies_movie"("movieId","actorId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "FK_45708bd514560bac8a3a54470d5" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP COLUMN "awardId"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD "awardId" bigint`);
//         await queryRunner.query(`ALTER TABLE "award" DROP CONSTRAINT "PK_e887e4e69663925ebb60d3a7775"`);
//         await queryRunner.query(`ALTER TABLE "award" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "award" ADD "id" bigint NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "award" ADD CONSTRAINT "PK_e887e4e69663925ebb60d3a7775" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD CONSTRAINT "FK_3cd871b4c3635fb5e6cbcb3b668" FOREIGN KEY ("awardId") REFERENCES "award"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         // await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "PK_05b325494fcc996a44ae6928e5e"`);
//         await queryRunner.query(`ALTER TABLE "actor" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "actor" ADD "id" BIGSERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "PK_05b325494fcc996a44ae6928e5e" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "actor_movies_movie" ADD CONSTRAINT "FK_48fa78b2634b01bf58ad1686ef5" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "director" DROP CONSTRAINT "PK_b85b179882f31c43324ef124fea"`);
//         await queryRunner.query(`ALTER TABLE "director" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "director" ADD "id" BIGSERIAL NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "director" ADD CONSTRAINT "PK_b85b179882f31c43324ef124fea" PRIMARY KEY ("id")`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD CONSTRAINT "FK_a32a80a88aff67851cf5b75d1cb" FOREIGN KEY ("directorId") REFERENCES "director"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "updated_at"`);
//         await queryRunner.query(`ALTER TABLE "movie" DROP COLUMN "created_at"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP CONSTRAINT "PK_d37431a574500c808f3a800cac4"`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" ADD CONSTRAINT "PK_e592fd44ed9b5cfd791a9d5d8eb" PRIMARY KEY ("year")`);
//         await queryRunner.query(`ALTER TABLE "movie_actor_award" DROP COLUMN "id"`);
//         await queryRunner.query(`ALTER TABLE "award" DROP COLUMN "uuid"`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
//         await queryRunner.query(`ALTER TABLE "movie" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
//     }

// }
